network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [193.191.177.171/25, 2001:6a8:2880:a077::ab/64]
      routes:    
        - to: default
          via: 193.191.177.254
        - to: default
          via: 2001:6a8:2880:a077::1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
