#!/bin/bash
echo "$#"
if [[ "$1" = "-t" ]]
then
        if [[ "$2" = "A" ]]
        then
                FILE=/etc/bind/generated/db."$5"
                if [[ -f "$FILE" ]]
                then
                        echo "$3        IN      A       $4" >> "$FILE"
                        nummer=$(grep -Po '\d+(?=\s+; Serial)' "$FILE")
                        npe=$(($nummer + 1))
                        half=$(grep -Po '\s+; Serial' "$FILE")
                        full=$(grep -Po '\d+\s+; Serial' "$FILE")
                        sed -i "s/$full/$npe$half/g" "$FILE"
                else
                        echo "not an existing file"
                        exit 0
                fi

        elif [[ "$2" = "MX" ]]
        then
                FILE=/etc/bind/generated/db."$4"
                if [[ -f "$FILE" ]]
                then
                        echo "$3        IN	CNAMZ       $4." >> "$FILE"
                        nummer=$(grep -Po '\d+(?=\s+; Serial)' "$FILE")
                        npe=$(($nummer + 1))
                        half=$(grep -Po '\s+; Serial' "$FILE")
                        full=$(grep -Po '\d+\s+; Serial' "$FILE")
                        sed -i "s/$full/$npe$half/g" "$FILE"
                else
                        echo "not an existing file"
                        exit 0
                fi

        elif [[ "$2" = "CNAME" ]]
        then
                FILE=/etc/bind/generated/db."$4"
                if [[ -f "$FILE" ]]
                then
			
                        echo "$3        IN      A       $4" >> "$FILE"
                        nummer=$(grep -Po '\d+(?=\s+; Serial)' "$FILE")
                        npe=$(($nummer + 1))
                        half=$(grep -Po '\s+; Serial' "$FILE")
                        full=$(grep -Po '\d+\s+; Serial' "$FILE")
                        sed -i "s/$full/$npe$half/g" "$FILE"
                else
                        echo "not an existing file"
                        exit 0
                fi

        else
                echo "invalid option"
                exit 0
        fi
elif [[ "$#" != 3 ]]
then
        echo "not the correct amount of arguments"
        exit 0
else
        FILE=/etc/bind/generated/db."$3"
        if [[ -f "$FILE" ]]
        then
                echo "$1        IN      A       $2" >> "$FILE"
                nummer=$(grep -Po '\d+(?=\s+; Serial)' "$FILE")
                npe=$(($nummer + 1))
                half=$(grep -Po '\s+; Serial' "$FILE")
                full=$(grep -Po '\d+\s+; Serial' "$FILE")
                sed -i "s/$full/$npe$half/g" "$FILE"
        else
                echo "not an existing file"
                exit 0
        fi
fi
systemctl reload bind9
exit 0
